version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "${WWW_PORT}:80"
    links:
      - mysql5
    networks:
      - default
    volumes:
      - type: bind
        source: ./config
        target: /var/www/html/config
      - type: bind
        source: ./storage
        target: /var/www/html/storage
      - type: bind
        source: ./userfiles/media
        target: /var/www/html/userfiles/media
      - ./:/var/www/html/:delegated
  mysql5:
    image: mysql:5.7.28
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql5data:/var/lib/mysql
  myadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    links:
      - mysql5:db
    ports:
      - ${MY_ADMIN_PORT}:80
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
volumes:
  storage:
  config:
  media:
  mysql5data:
  mysql5:
  myadmin: